@startuml

!pragma useVerticalIf on

start

if (Number of docks?) then (greater than 1)
    :Genetic algorithm;
else
    if (Number of vessels) then (greater or equal then 9)
        :Genetic algorithm;
    elseif (lower then 9)
        :Heuristic method;
    elseif (lower then 7)
        :Optimal method;
    else 
    endif
endif

end

@enduml