@startuml AlgorithmSelection_SD

actor user as "User"

box "System"
participant http as "HttpServerController"
participant schService as "ScheduleService"
participant Optimal
participant Heuristic
participant Genetic
end box


user --> http : Send request for schedule with necessary data
activate http

http -> schService
activate schService

alt number of docks <= 1

    alt number of vessels <= 6

        schService -> Optimal
        activate Optimal
        Optimal -> schService : Return Schedule
        deactivate Optimal

    else number of vessels > 6

        schService -> Heuristic
        activate Heuristic
        Heuristic -> schService : Return Schedule
        deactivate Heuristic

    end

else number of docks > 1

    schService -> Genetic 
    activate Genetic
    Genetic -> schService : Return Schedule
    deactivate Genetic

end


schService -> http
deactivate schService

http --> user : Send in created schedule
deactivate http


@enduml